eCommerce.Web/ViewModels/HomeViewModels.cs
using eCommerce.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCommerce.Web.ViewModels
{
    public class HomeSlidersViewModel
    {
        public List<Configuration> SlidersConfigurations { get; set; }
    }
}

eCommerce.Web/ViewModels/SearchFiltersViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCommerce.Web.ViewModels
{
    public class PriceRangeFilterViewModel
    {
        public decimal? PriceFrom { get; set; }
        public decimal? PriceTo { get; set; }
        public decimal MaxPrice { get; set; }
    }
}

eCommerce.Web/Controllers/CategoriesController.cs
using eCommerce.Services;
using eCommerce.Shared.Helpers;
using eCommerce.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Web.Controllers
{
    public class CategoriesController : PublicBaseController
    {
        [OutputCache(Duration = 60, VaryByParam = "lang")]
        public ActionResult CategoriesMenu(string lang)
        {
            CategoriesMenuViewModel model = new CategoriesMenuViewModel();

            var categories = CategoriesService.Instance.GetCategories();

            if(categories != null && categories.Count > 0)
            {
                //remove uncategorized category from categories list.
                categories = categories.Where(x => x.ID != 1).ToList();

                model.CategoryWithChildrens = CategoryHelpers.MakeCategoriesHierarchy(categories);
            }

            return PartialView("_CategoriesMenu", model);
        }

        public ActionResult CategoriesMenuForMobile()
        {
            if (AppDataHelper.IsMobile)
            {
                CategoriesMenuViewModel model = new CategoriesMenuViewModel();

                var categories = CategoriesService.Instance.GetCategories();

                if (categories != null && categories.Count > 0)
                {
                    //remove uncategorized category from categories list.
                    categories = categories.Where(x => x.ID != 1).ToList();

                    model.CategoryWithChildrens = CategoryHelpers.MakeCategoriesHierarchy(categories);
                }

                return PartialView("_CategoriesMenuForMobile", model);
            }
            else return null;
        }

        public ActionResult OurMenuCategories()
        {
            CategoriesMenuViewModel model = new CategoriesMenuViewModel();

            var categories = CategoriesService.Instance.GetCategories();

            if (categories != null && categories.Count > 0)
            {
                //remove uncategorized category from categories list.
                categories = categories.Where(x => x.ID != 1).ToList();

                model.CategoryWithChildrens = CategoryHelpers.MakeCategoriesHierarchy(categories);
            }

            return PartialView("_OurMenuCategories", model);
        }

        public ActionResult FeaturedCategories(int recordSize = 3)
        {
            var categories = CategoriesService.Instance.GetFeaturedCategories(recordSize: recordSize);

            return PartialView("_FeaturedCategoriesHomeSection", categories);
        }

        public ActionResult ProductsByFeaturedCategories(int recordSize = 3)
        {
            ProductsByFeaturedCategoriesViewModel model = new ProductsByFeaturedCategoriesViewModel
            {
                Categories = CategoriesService.Instance.GetFeaturedCategories(recordSize: recordSize)
            };

            return PartialView("_ProductsByFeaturedCategories", model);
        }
    }
}

eCommerce.Web/Controllers/HomeController.cs
using eCommerce.Entities;
using eCommerce.Services;
using eCommerce.Shared;
using eCommerce.Shared.Enums;
using eCommerce.Shared.Extensions;
using eCommerce.Shared.Helpers;
using eCommerce.Web.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Web.Controllers
{
    public class HomeController : PublicBaseController
    {
        public ActionResult Index()
        {
            /* if multi language is enabled and the home page is accessed without any language, redirect to the default language */
            if(ConfigurationsHelper.EnableMultilingual && Request.Url.AbsolutePath.ToString().Equals("/"))
            {
                return Redirect(Url.Home());
            }

            return View(new PageViewModel());
        }

        //[OutputCache(Duration = 600)]
        public ActionResult HomeSliders()
        {
            HomeSlidersViewModel model = new HomeSlidersViewModel
            {
                SlidersConfigurations = ConfigurationsService.Instance.GetConfigurationsByType((int)ConfigurationTypes.Sliders)
            };

            return PartialView("_BannerSlider", model);
        }

        public ActionResult Search(string category, string q, decimal? from, decimal? to, string sortby, int? pageNo, int? recordSize)
        {
            recordSize = recordSize ?? (int)RecordSizeEnums.Size20;

            ProductsViewModel model = new ProductsViewModel
            {
                Categories = CategoriesService.Instance.GetCategories()
            };

            if (!string.IsNullOrEmpty(category))
            {
                var selectedCategory = CategoriesService.Instance.GetCategoryByName(category);

                if (selectedCategory == null) return HttpNotFound();
                else
                {
                    model.CategoryID = selectedCategory.ID;
                    model.CategoryName = selectedCategory.SanitizedName;
                    model.SelectedCategory = selectedCategory;

                    model.SearchedCategories = CategoryHelpers.GetAllCategoryChildrens(selectedCategory, model.Categories);
                }
            }
            
            model.SearchTerm = q;
            model.PriceFrom = from;
            model.PriceTo = to;
            model.SortBy = sortby;
            model.PageSize = recordSize;
            
            var selectedCategoryIDs = model.SearchedCategories != null ? model.SearchedCategories.Select(x => x.ID).ToList() : null;

            model.Products = ProductsService.Instance.SearchProducts(selectedCategoryIDs, model.SearchTerm, model.PriceFrom, model.PriceTo, model.SortBy, pageNo, recordSize.Value, activeOnly: true, out int count, stockCheckCount: null);

            model.Pager = new Pager(count, pageNo, recordSize.Value);

            return View(model);
        }

        public ActionResult PriceRangeFilter(decimal? priceFrom, decimal? priceTo)
        {
            var model = new PriceRangeFilterViewModel
            {
                PriceFrom = priceFrom,
                PriceTo = priceTo,

                MaxPrice = ProductsService.Instance.GetMaxProductPrice()
            };

            return PartialView("SearchFilters/_PriceRangeFilter", model);
        }

        [ValidateAntiForgeryToken]
        public JsonResult SubscribeNewsLetter(string email)
        {
            JsonResult jsonResult = new JsonResult();

            var newsletterSubscription = new NewsletterSubscription()
            {
                EmailAddress = email,
                IsVerified = false,
                UserID = User.Identity.IsAuthenticated ? User.Identity.GetUserId() : string.Empty,
                ModifiedOn = DateTime.Now,
                IsActive = true
            };

            var result = SharedService.Instance.SaveNewsletterSubscription(newsletterSubscription);

            if(result)
            {
                jsonResult.Data = new
                {
                    Success = true,
                    Message = "PP.Footer.NewsLetter.NewsletterSubscribed".LocalizedString()
                };
            }
            else
            {
                jsonResult.Data = new
                {
                    Success = false,
                    Message = "PP.Footer.NewsLetter.NewsletterAlreadySubscribed".LocalizedString()
                };
            }

            return jsonResult;
        }

        [ValidateAntiForgeryToken]
        public async Task<JsonResult> SubmitContactForm(string subject, string name, string email, string message)
        {
            JsonResult jsonResult = new JsonResult();

            try
            {
                //send order placed notification email to admin emails
                await new EmailService()
                                 .SendToEmailAsync(ConfigurationsHelper.SendGrid_FromEmailAddressName,
                                                   ConfigurationsHelper.SendGrid_FromEmailAddress,
                                                   ConfigurationsHelper.AdminEmailAddress,
                                                   EmailTextHelpers.ContactMessageSubject_Admin(),
                                                   EmailTextHelpers.ContactMessageBody_Admin(subject, name, email, message));

                jsonResult.Data = new
                {
                    Success = true,
                    Message = "Your message has been submitted. We will contact you back soon."
                };
            }
            catch (Exception)
            {
                jsonResult.Data = new
                {
                    Success = false,
                    Message = "An error occured while submitting your message."
                };
            }

            return jsonResult;
        }
    }
}

eCommerce.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

eCommerce.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

eCommerce.Web/Views/Home/Index.Mobile.cshtml
@model eCommerce.Web.ViewModels.PageViewModel

@{
    if (Model != null)
    {
        Model.PageTitle = "PP.Home.Title".LocalizedString();
        Model.PageDescription = "PP.Home.Description".LocalizedString();
        Model.PageURL = Url.Home();
        Model.PageImageURL = PictureHelper.PageImageURL("home.jpg");
    }

    Html.RenderAction("HomeSliders", "Home");
    <br />
    Html.RenderAction("ProductsByFeaturedCategories", "Categories", new { recordSize = 3 });
}

<div class="container-fluid my-4 pb-4">
    <div class="row">
        <div class="col-lg-12">
            <div class="loading-more">
                <i class="fas fa-search"></i>
                <a href="@Url.SearchProducts()">
                    @("PP.Home.SearchMoreProducts".LocalizedString())
                </a>
            </div>
        </div>
    </div>
</div>

@if (true)
{
    <section class="latest-blog spad py-0">
        <div class="benefit-items">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="single-benefit">
                            <div class="sb-icon">
                                <i class="fas fa-shipping-fast"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.FastDelivery".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.OnTimeDelivery".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-benefit">
                            <div class="sb-icon">
                                <i class="fas fa-headset"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.247Support".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.AlwaysReadyToHelp".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-benefit border-0">
                            <div class="sb-icon">
                                <i class="fas fa-user-shield"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.SecurePayments".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.SecurePaymentOptions".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="partner-logo" title="@("PP.Home.Showcase.OurPartners".LocalizedString())">
        <div class="container">
            <div class="logo-carousel owl-carousel">
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-2.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-2.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
}

eCommerce.Web/Views/Home/Index.cshtml
@model eCommerce.Web.ViewModels.PageViewModel


@{
    if (Model != null)
    {
        Model.PageTitle = "PP.Home.Title".LocalizedString();
        Model.PageDescription = "PP.Home.Description".LocalizedString();
        Model.PageURL = Url.Home();
        Model.PageImageURL = PictureHelper.PageImageURL("home.jpg");

        Html.RenderAction("HomeSliders", "Home");
        Html.RenderAction("OurMenuCategories", "Categories");
        Html.RenderAction("FeaturedCategories", "Categories", new { recordSize = 3, isForHomePage = true });
        Html.RenderAction("ProductsByFeaturedCategories", "Categories", new { recordSize = 7 });
    }
}

@*<section class="homeSectionFour text-center">
    <div class="container">
        <div class="heading">
            <img src="~/Content/greeno-theme/images/head_img.png" alt="">
            <h2>
                Best Sellers
            </h2>
        </div>
        <div class="owl-carousel owl-theme owl-dots-hidden product-carousel">
            <div class="item product-style-1">
                <div class="inner">
                    <span class="percent badge badge-sale">30% OFF</span>
                    <a href="#" class="quick-view">
                        <span class="main-icon-eye"></span>
                        <span class="c-tooltip">Quick View</span>
                    </a>
                    <div class="product-image">
                        <img src="~/Content/greeno-theme/images/silm-fest-1.png" alt="">
                    </div>
                    <div class="info">
                        <a href="#" class="title">
                            <span>Slim Fest</span>
                        </a>
                        <div class="price">
                            <span class="current">224.00 Rs</span>
                            <span class="old">320.00 Rs</span>
                        </div>
                        <button class="btn btn-rounded btn-green">Select Options</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>*@
<section class="homeSectionFive">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <img src="~/Content/greeno-theme/images/1-2.png" alt="">
            </div>
            <div class="col-12 col-md-4">
                <img src="~/Content/greeno-theme/images/2-2.png" alt="">
            </div>
            <div class="col-12 col-md-4">
                <img src="~/Content/greeno-theme/images/3-2.png" alt="">
            </div>
        </div>
    </div>
</section>


@*<div class="container-fluid my-4 pb-4">
        <div class="row">
            <div class="col-lg-12">
                <div class="loading-more">
                    <i class="fas fa-search"></i>
                    <a href="@Url.SearchProducts()">
                        @("PP.Home.SearchMoreProducts".LocalizedString())
                    </a>
                </div>
            </div>
        </div>
    </div>*@

@if (true)
{
    @*<section class="latest-blog spad py-0">
        <div class="benefit-items">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="single-benefit">
                            <div class="sb-icon">
                                <i class="fas fa-shipping-fast"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.FastDelivery".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.OnTimeDelivery".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-benefit">
                            <div class="sb-icon">
                                <i class="fas fa-headset"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.247Support".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.AlwaysReadyToHelp".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-benefit border-0">
                            <div class="sb-icon">
                                <i class="fas fa-user-shield"></i>
                            </div>
                            <div class="sb-text">
                                <h6>@("PP.Home.Showcase.SecurePayments".LocalizedString())</h6>
                                <p>@("PP.Home.Showcase.SecurePaymentOptions".LocalizedString())</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="partner-logo" title="@("PP.Home.Showcase.OurPartners".LocalizedString())">
        <div class="container">
            <div class="logo-carousel owl-carousel">
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-2.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-2.png" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="~/Content/templates/fashi/img/logo-carousel/logo-1.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>*@
}


@section IncludeFooterStyleScripts {
    <script type="text/javascript">
        $('.owl-carousel').owlCarousel({
            loop: true,
            margin: 30,
            nav: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 4
                }
            }
        })
    </script>
}

eCommerce.Web/Views/Home/Search.cshtml
@using eCommerce.Entities
@using eCommerce.Shared.Enums
@model eCommerce.Web.ViewModels.ProductsViewModel

@{
    CategoryRecord currentLanguageCategoryRecord = null;

    var haveParentCategory = false;

    if (Model != null)
    {

        if (Model.SelectedCategory != null)
        {
            currentLanguageCategoryRecord = Model.SelectedCategory.CategoryRecords.FirstOrDefault(x => x.LanguageID == AppDataHelper.CurrentLanguage.ID);

            Model.PageTitle = "PP.Search.TitleWithCategory".LocalizedString().Replace("{category}", currentLanguageCategoryRecord != null ? currentLanguageCategoryRecord.Name : Model.SelectedCategory.SanitizedName).Replace("{application}", ConfigurationsHelper.ApplicationName);
            Model.PageDescription = currentLanguageCategoryRecord != null ? currentLanguageCategoryRecord.Summary : string.Empty;
            Model.PageURL = Url.SearchProducts(category: Model.SelectedCategory.SanitizedName, q: Model.SearchTerm);


            haveParentCategory = Model.SelectedCategory.ParentCategory != null;
        }
        else
        {
            Model.PageTitle = "PP.Search.Title".LocalizedString().Replace("{application}", ConfigurationsHelper.ApplicationName);
            Model.PageDescription = "PP.Search.Description".LocalizedString();
            Model.PageURL = Url.SearchProducts(q: Model.SearchTerm);
        }

        Model.PageImageURL = PictureHelper.PageImageURL("search.jpg");
    }

    ViewBag.SearchTerm = Model.SearchTerm;

}

<input id="searchURL" type="hidden" value="@Url.SearchProducts(category: !string.IsNullOrEmpty(Model.CategoryName) ? Model.CategoryName : string.Empty, q: Model.SearchTerm)" />

@*<div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text product-more">
                        <a href="@Url.Home()">
                            <i class="fas fa-home mr-1"></i>
                            @("PP.Header.Menu.Home".Localized())
                        </a>
                        @if (currentLanguageCategoryRecord != null)
                        {
                            <a href="@Url.SearchProducts()">@("PP.Search.SearchProducts".Localized())</a>
                            if (haveParentCategory)
                            {
                                var currentLanguageParentCategoryRecord = Model.SelectedCategory.ParentCategory.CategoryRecords.FirstOrDefault(x => x.LanguageID == AppDataHelper.CurrentLanguage.ID);

                                <a href="@Url.SearchProducts(category: Model.SelectedCategory.ParentCategory.SanitizedName)">@(currentLanguageParentCategoryRecord != null ? currentLanguageParentCategoryRecord.Name : string.Empty)</a>
                            }
                            <span>@(currentLanguageCategoryRecord.Name)</span>
                        }
                        else
                        {
                            <span>@("PP.Search.SearchProducts".Localized())</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>*@


<section class="orderSectionOne productListing">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 sidebartop">
                <div class="sidebar">
                    <div class="sidebar__inner">
                        @{
                            Html.RenderPartial("_SearchFilters", Model);
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-9 ml-auto">
                <div class="banner">
                    <img src="~/Content/greeno-theme/images/product-listing-top.jpg" alt="">
                </div>
                
                    @{
                        Html.RenderPartial("_Search", Model);
                    }
                
            </div>
        </div>
    </div>
</section>





@*<section class="product-shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">

                </div>
                <div class="col-lg-9 order-1 order-lg-2">

                </div>
            </div>
        </div>
    </section>*@

eCommerce.Web/Views/Home/_BannerSlider.cshtml
@model eCommerce.Web.ViewModels.HomeSlidersViewModel

@if (Model != null && Model.SlidersConfigurations != null && Model.SlidersConfigurations.Count > 0)
{
    var i = 0;
    var j = 0;
    <section class="homeSectionOne">
        <div id="carouselIndicators" class="home-slider-carousel carousel slide" data-ride="carousel">
            @if (Model.SlidersConfigurations.Count > 1)
            {
                <ol class="carousel-indicators home-carousel-indicators">
                    @foreach (var slider in Model.SlidersConfigurations)
                    {
                        <li data-target="#carouselIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : string.Empty)"></li>

                        i++;
                    }
                </ol>
            }
            <div class="carousel-inner home-carousel-inner" role="listbox">
                @foreach (var configuration in Model.SlidersConfigurations)
                {
                    @* TODO: Localizing Slider *@

                    var img = configuration.Value.GetSubstringText("#IMG#", "#TH#");
                    var topHeading = configuration.Value.GetSubstringText("#TH#", "#PG#");
                    var paragraph = configuration.Value.GetSubstringText("#PG#", "#LK#");
                    var link = configuration.Value.GetSubstringText("#LK#", "");

                    if (!string.IsNullOrEmpty(img))
                    {
                        img = img.Replace("IMG#", "");
                    }
                    if (!string.IsNullOrEmpty(topHeading))
                    {
                        topHeading = topHeading.Replace("TH#", "");
                    }
                    if (!string.IsNullOrEmpty(paragraph))
                    {
                        paragraph = paragraph.Replace("PG#", "");
                    }
                    if (!string.IsNullOrEmpty(link))
                    {
                        link = link.Replace("LK#", "");
                    }

                    <div class="carousel-item text-center @(j == 0 ? "active" : string.Empty)">
                        @*@Html.Picture(img, classes: "img-fluid", alt: "Slider")*@
                        <img src="~/Content/images/@img" alt="">

                        @*@if (!string.IsNullOrEmpty(topHeading) || !string.IsNullOrEmpty(paragraph) || !string.IsNullOrEmpty(link))
                            {
                                <div class="carousel-caption">
                                    <a href="@link.IfNullOrEmptyShowAlternative("#")">
                                        <h5>@topHeading</h5>
                                        <p>@paragraph</p>
                                    </a>
                                </div>
                            }*@
                    </div>

                    j++;
                }
            </div>
            @if (Model.SlidersConfigurations.Count > 1)
            {
                <a class="carousel-control-prev home-carousel-prev" href="#carouselIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next home-carousel-next" href="#carouselIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            }
        </div>
        <div class="strip strip-green text-center">
            <h5 class="text">
                Free standard shipping on order over Rs400 <a class="underline" href="#">Learn More</a>
            </h5>
        </div>
    </section>

}

eCommerce.Web/Views/Home/_HomeSliders.cshtml
@model eCommerce.Web.ViewModels.HomeSlidersViewModel

@if (Model != null && Model.SlidersConfigurations != null && Model.SlidersConfigurations.Count > 0)
{
	var i = 0;
	var j = 0;

	<div class="row">
		<div class="col-lg-12">
			<div id="carouselExampleIndicators" class="carousel slide mb-2" data-ride="carousel">
				<ol class="carousel-indicators">

					@foreach (var slider in Model.SlidersConfigurations)
					{
						<li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : string.Empty)"></li>

						i++;
					}
				</ol>
				<div class="carousel-inner" role="listbox">
					@foreach (var slider in Model.SlidersConfigurations)
					{
						<div class="carousel-item @(j == 0 ? "active" : string.Empty)">
							@Html.Picture(slider.Value, classes: "d-block img-fluid", alt: "Slider")
						</div>

						j++;
					}
				</div>
				<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
}

eCommerce.Web/Views/Home/_SearchFilters.cshtml
@using eCommerce.Entities
@using eCommerce.Shared
@model eCommerce.Web.ViewModels.ProductsViewModel

@if (Model != null)
{
    Html.RenderPartial("SearchFilters/_SearchInputFilter", Model);

    Html.RenderPartial("SearchFilters/_CategoriesFilter", Model);

    Html.RenderAction("PriceRangeFilter", new { priceFrom = Model.PriceFrom, priceTo = Model.PriceTo });
}